default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 10 } %>
  user: <%= ENV.fetch("PG_USER") %>
  password: <%= ENV.fetch("PG_PASSWORD") %>
  timeout: 5000

development:
  <<: *default
  database: develop_medical_center

test:
  <<: *default
  database: test_medical_center

production:
  adapter: postgresql
  database: production_medical_center
  pool: 10
  timeout: 5000
  user: <%= Rails.application.credentials.db_user %>
  password: <%= Rails.application.credentials.db_password %>
